const fs = require('fs');
const tr = {
'restaurant.title':['Restoran','Ресторан','Restaurant'],
'restaurant.subtitle':['Restoran idarəetməsi','Управление рестораном','Restaurant Management'],
'restaurant.today':['Bu gün','Сегодня','Today'],
'restaurant.yesterday':['Dünən','Вчера','Yesterday'],
'restaurant.thisWeek':['Bu həftə','На этой неделе','This Week'],
'restaurant.thisMonth':['Bu ay','В этом месяце','This Month'],
'restaurant.customRange':['Xüsusi aralıq...','Свой диапазон...','Custom Range...'],
'restaurant.selectDateRange':['Tarix aralığını seçin','Выберите диапазон','Select Date Range'],
'restaurant.selectEndDate':['Bitmə tarixini seçin','Выберите конечную дату','Select End Date'],
'restaurant.applyRange':['Tətbiq et','Применить','Apply'],
'restaurant.clear':['Təmizlə','Очистить','Clear'],
'restaurant.tables':['Masalar','Столы','Tables'],
'restaurant.table':['Masa','Стол','Table'],
'restaurant.orders':['Sifarişlər','Заказы','Orders'],
'restaurant.staff':['Heyət','Персонал','Staff'],
'restaurant.menuDishes':['Menyu','Меню','Menu'],
'restaurant.reportsAnalytics':['Hesabatlar','Аналитика','Analytics'],
'restaurant.kitchenDisplay':['Mətbəx','Кухня','Kitchen'],
'restaurant.floorPlan':['Zal planı','План зала','Floor Plan'],
'restaurant.tablesSettings':['Masa tənzimləmələri','Настройки столов','Table Settings'],
'restaurant.securityAttendance':['Təhlükəsizlik','Безопасность','Security'],
'restaurant.staffWaiters':['Ofisiantlar','Официанты','Waiters'],
'restaurant.inventory':['İnventar','Инвентарь','Inventory'],
'restaurant.addTable':['Masa əlavə et','Добавить стол','Add Table'],
'restaurant.addOrder':['Sifariş əlavə et','Добавить заказ','Add Order'],
'restaurant.addStaff':['Heyət əlavə et','Добавить сотрудника','Add Staff'],
'restaurant.addDish':['Yemək əlavə et','Добавить блюдо','Add Dish'],
'restaurant.addNewDish':['Yeni yemək','Новое блюдо','New Dish'],
'restaurant.addNewStaff':['Yeni işçi','Новый сотрудник','New Staff'],
'restaurant.addCategory':['Kateqoriya əlavə et','Добавить категорию','Add Category'],
'restaurant.addIngredient':['İnqrediyent əlavə et','Добавить ингредиент','Add Ingredient'],
'restaurant.addIngredientBtn':['Əlavə et','Добавить','Add'],
'restaurant.addNote':['Qeyd əlavə et','Добавить примечание','Add Note'],
'restaurant.addPlace':['Yer əlavə et','Добавить место','Add Place'],
'restaurant.editDish':['Yeməyi redaktə et','Редактировать блюдо','Edit Dish'],
'restaurant.editPlace':['Yeri redaktə et','Редактировать место','Edit Place'],
'restaurant.editStaff':['İşçini redaktə et','Редактировать сотрудника','Edit Staff'],
'restaurant.editRecipe':['Resepti redaktə et','Редактировать рецепт','Edit Recipe'],
'restaurant.saveDish':['Yeməyi saxla','Сохранить блюдо','Save Dish'],
'restaurant.saveStaff':['Saxla','Сохранить','Save Staff'],
'restaurant.saveRecipe':['Resepti saxla','Сохранить рецепт','Save Recipe'],
'restaurant.saveChanges':['Dəyişiklikləri saxla','Сохранить изменения','Save Changes'],
'restaurant.deleteDish':['Yeməyi sil','Удалить блюдо','Delete Dish'],
'restaurant.deleteDishConfirm':['Bu yeməyi silmək istəyirsiniz?','Удалить это блюдо?','Delete this dish?'],
'restaurant.deletePlace':['Yeri sil','Удалить место','Delete Place'],
'restaurant.deletePlaceConfirm':['Bu yeri silmək istəyirsiniz?','Удалить это место?','Delete this place?'],
'restaurant.removeStaff':['İşçini çıxar','Удалить сотрудника','Remove Staff'],
'restaurant.removeStaffConfirm':['Bu işçini çıxarmaq istəyirsiniz?','Удалить этого сотрудника?','Remove this staff?'],
'restaurant.dishName':['Yemək adı','Название блюда','Dish Name'],
'restaurant.dishNamePlaceholder':['Yemək adını daxil edin','Введите название блюда','Enter dish name'],
'restaurant.categoryName':['Kateqoriya adı','Название категории','Category Name'],
'restaurant.categoryPlaceholder':['Kateqoriya adını daxil edin','Введите категорию','Enter category name'],
'restaurant.price':['Qiymət','Цена','Price'],
'restaurant.sellingPrice':['Satış qiyməti','Цена продажи','Selling Price'],
'restaurant.cost':['Maya dəyəri','Себестоимость','Cost'],
'restaurant.foodCost':['Yemək xərci','Стоимость продуктов','Food Cost'],
'restaurant.margin':['Marja','Маржа','Margin'],
'restaurant.category':['Kateqoriya','Категория','Category'],
'restaurant.allCategories':['Bütün kateqoriyalar','Все категории','All Categories'],
'restaurant.searchDishes':['Yemək axtar...','Поиск блюд...','Search dishes...'],
'restaurant.searchStaff':['Heyət axtar...','Поиск сотрудников...','Search staff...'],
'restaurant.searchIngredientsPlaceholder':['İnqrediyent axtar...','Поиск ингредиентов...','Search ingredients...'],
'restaurant.ingredient':['İnqrediyent','Ингредиент','Ingredient'],
'restaurant.ingredients':['İnqrediyentlər','Ингредиенты','Ingredients'],
'restaurant.recipeIngredients':['Resept inqrediyentləri','Ингредиенты рецепта','Recipe Ingredients'],
'restaurant.recipeSubtitle':['Resept detalları','Детали рецепта','Recipe Details'],
'restaurant.noRecipeItems':['Resept elementi yoxdur','Нет ингредиентов','No recipe items'],
'restaurant.maxPortions':['Max porsiya','Макс. порций','Max Portions'],
'restaurant.unit':['Vahid','Единица','Unit'],
'restaurant.gram':['qram','грамм','gram'],
'restaurant.kg':['kq','кг','kg'],
'restaurant.liter':['litr','литр','liter'],
'restaurant.pcs':['ədəd','шт','pcs'],
'restaurant.pack':['paket','пакет','pack'],
'restaurant.stock':['Stok','Запас','Stock'],
'restaurant.lowStock':['Az stok','Мало запасов','Low Stock'],
'restaurant.minStock':['Min stok','Мин. запас','Min Stock'],
'restaurant.outofstock':['Bitib','Нет в наличии','Out of Stock'],
'restaurant.inventoryValue':['İnventar dəyəri','Стоимость инвентаря','Inventory Value'],
'restaurant.stockWarningPrefix':['Diqqət: az stok','Внимание: мало запасов','Warning: low stock'],
'restaurant.role':['Vəzifə','Должность','Role'],
'restaurant.waiter':['Ofisiant','Официант','Waiter'],
'restaurant.bartender':['Barmen','Бармен','Bartender'],
'restaurant.chef':['Aşpaz','Повар','Chef'],
'restaurant.headwaiter':['Baş ofisiant','Старший официант','Head Waiter'],
'restaurant.manager':['Menecer','Менеджер','Manager'],
'restaurant.salary':['Maaş','Зарплата','Salary'],
'restaurant.shift':['Növbə','Смена','Shift'],
'restaurant.shiftStartTime':['Növbə başlanğıcı','Начало смены','Shift Start'],
'restaurant.morning':['Səhər','Утро','Morning'],
'restaurant.evening':['Axşam','Вечер','Evening'],
'restaurant.night':['Gecə','Ночь','Night'],
'restaurant.flexible':['Çevik','Гибкий','Flexible'],
'restaurant.attendance':['Davamiyyət','Посещаемость','Attendance'],
'restaurant.ontime':['Vaxtında','Вовремя','On time'],
'restaurant.late':['Gecikmə','Опоздание','Late'],
'restaurant.onleave':['İcazəli','В отпуске','On Leave'],
'restaurant.fullName':['Ad Soyad','ФИО','Full Name'],
'restaurant.staffMember':['Heyət üzvü','Сотрудник','Staff Member'],
'restaurant.staffPlaceholder':['İşçi adını daxil edin','Введите имя сотрудника','Enter staff name'],
'restaurant.loadingPersonnel':['Heyət yüklənir...','Загрузка персонала...','Loading personnel...'],
'restaurant.noPersonnel':['Heyət tapılmadı','Персонал не найден','No personnel found'],
'restaurant.selectStaffToBegin':['İşçi seçin','Выберите сотрудника','Select staff to begin'],
'restaurant.isMaster':['Baş menecer','Главный менеджер','Is Master'],
'restaurant.patternPassword':['Naxış parolu','Графический пароль','Pattern Password'],
'restaurant.setPattern':['Naxış təyin et','Установить паттерн','Set Pattern'],
'restaurant.changePattern':['Naxışı dəyiş','Изменить паттерн','Change Pattern'],
'restaurant.drawPatternInstructions':['Naxış çəkin','Нарисуйте паттерн','Draw a pattern'],
'restaurant.drawPatternToVerify':['Təsdiq üçün naxış çəkin','Нарисуйте паттерн для подтверждения','Draw pattern to verify'],
'restaurant.incorrectPattern':['Yanlış naxış','Неверный паттерн','Incorrect pattern'],
'restaurant.setStaffPattern':['Heyət naxışını təyin et','Установить паттерн сотрудника','Set Staff Pattern'],
'restaurant.authorizeAction':['Əməliyyatı təsdiqlə','Авторизуйте действие','Authorize Action'],
'restaurant.tableConfig':['Masa konfiqurasiyası','Конфигурация столов','Table Configuration'],
'restaurant.tableConfigDesc':['Masaları idarə edin','Управляйте столами','Manage tables'],
'restaurant.tablePlaceholder':['Masa adını daxil edin','Введите название стола','Enter table name'],
'restaurant.nameNumber':['Ad/Nömrə','Имя/Номер','Name/Number'],
'restaurant.capacity':['Tutum','Вместимость','Capacity'],
'restaurant.maxCapacity':['Max tutum','Макс. вместимость','Max Capacity'],
'restaurant.type':['Növ','Тип','Type'],
'restaurant.mainHall':['Əsas zal','Основной зал','Main Hall'],
'restaurant.vipCabin':['VIP kabin','VIP кабина','VIP Cabin'],
'restaurant.bar':['Bar','Бар','Bar'],
'restaurant.barStool':['Bar stulu','Барный стул','Bar Stool'],
'restaurant.depositRequired':['Depozit tələb olunur','Требуется депозит','Deposit Required'],
'restaurant.requiresDeposit':['Depozit lazımdır','Необходим депозит','Requires Deposit'],
'restaurant.createPlace':['Yer yarat','Создать место','Create Place'],
'restaurant.createCategory':['Kateqoriya yarat','Создать категорию','Create Category'],
'restaurant.tableStatus':['Masa statusu','Статус стола','Table Status'],
'restaurant.free':['Boş','Свободен','Free'],
'restaurant.occupied':['Məşğul','Занят','Occupied'],
'restaurant.reserved':['Rezerv','Забронирован','Reserved'],
'restaurant.available':['Mövcud','Доступен','Available'],
'restaurant.active':['Aktiv','Активный','Active'],
'restaurant.noTables':['Masa yoxdur','Столов нет','No Tables'],
'restaurant.tableEmpty':['Masa boşdur','Стол пуст','Table Empty'],
'restaurant.allTables':['Bütün masalar','Все столы','All Tables'],
'restaurant.allStatuses':['Bütün statuslar','Все статусы','All Statuses'],
'restaurant.seatGuests':['Qonaqları yerləşdir','Посадить гостей','Seat Guests'],
'restaurant.assignGuests':['Qonaqları təyin et','Назначить гостей','Assign Guests'],
'restaurant.persons':['nəfər','чел.','persons'],
'restaurant.assignedWaiter':['Təyin edilmiş ofisiant','Назначенный официант','Assigned Waiter'],
'restaurant.changeWaiter':['Ofisiantı dəyiş','Сменить официанта','Change Waiter'],
'restaurant.activeOrder':['Aktiv sifariş','Активный заказ','Active Order'],
'restaurant.noActiveOrders':['Aktiv sifariş yoxdur','Нет активных заказов','No Active Orders'],
'restaurant.noOrders':['Sifariş yoxdur','Заказов нет','No Orders'],
'restaurant.selectItems':['Məhsulları seçin','Выберите позиции','Select Items'],
'restaurant.doneOrdering':['Sifariş tamamlandı','Заказ завершён','Done Ordering'],
'restaurant.sendToKitchen':['Mətbəxə göndər','Отправить на кухню','Send to Kitchen'],
'restaurant.currentBill':['Cari hesab','Текущий счёт','Current Bill'],
'restaurant.checkout':['Hesabı bağla','Оплата','Checkout'],
'restaurant.cancelOrder':['Sifarişi ləğv et','Отменить заказ','Cancel Order'],
'restaurant.cancelConfirm':['Sifarişi ləğv etmək istəyirsiniz?','Отменить заказ?','Cancel this order?'],
'restaurant.cancelItemConfirm':['Bu məhsulu ləğv etmək istəyirsiniz?','Отменить эту позицию?','Cancel this item?'],
'restaurant.itemCancelled':['Məhsul ləğv edildi','Позиция отменена','Item Cancelled'],
'restaurant.tooLateToCancel':['Ləğv etmək üçün çox gec','Слишком поздно для отмены','Too late to cancel'],
'restaurant.newItems':['Yeni məhsullar','Новые позиции','New Items'],
'restaurant.items':['Məhsullar','Позиции','Items'],
'restaurant.amount':['Məbləğ','Сумма','Amount'],
'restaurant.time':['Vaxt','Время','Time'],
'restaurant.date':['Tarix','Дата','Date'],
'restaurant.timeSeated':['Oturma vaxtı','Время посадки','Time Seated'],
'restaurant.viewAllOrders':['Bütün sifarişlər','Все заказы','View All Orders'],
'restaurant.mergeTables':['Masaları birləşdir','Объединить столы','Merge Tables'],
'restaurant.selectToMerge':['Birləşdirmək üçün seçin','Выберите для объединения','Select to Merge'],
'restaurant.confirmMerge':['Birləşdirməyi təsdiqlə','Подтвердить объединение','Confirm Merge'],
'restaurant.cancelMerge':['Birləşdirməni ləğv et','Отменить объединение','Cancel Merge'],
'restaurant.unmerge':['Ayır','Разъединить','Unmerge'],
'restaurant.moveTable':['Masanı köçür','Переместить стол','Move Table'],
'restaurant.selectNewTable':['Yeni masa seçin','Выберите новый стол','Select New Table'],
'restaurant.moveSuccess':['Köçürüldü','Перемещено','Moved Successfully'],
'restaurant.cancelMove':['Köçürməni ləğv et','Отменить перемещение','Cancel Move'],
'restaurant.actions':['Əməliyyatlar','Действия','Actions'],
'restaurant.kitchenQueue':['Mətbəx növbəsi','Очередь на кухне','Kitchen Queue'],
'restaurant.kitchen':['Mətbəx','Кухня','Kitchen'],
'restaurant.noData':['Məlumat yoxdur','Нет данных','No Data'],
'restaurant.performanceDashboard':['Performans paneli','Панель производительности','Performance Dashboard'],
'restaurant.performanceDesc':['Ətraflı analitika','Подробная аналитика','Detailed analytics'],
'restaurant.totalRevenue':['Ümumi gəlir','Общий доход','Total Revenue'],
'restaurant.totalExpenses':['Ümumi xərclər','Общие расходы','Total Expenses'],
'restaurant.netProfit':['Xalis mənfəət','Чистая прибыль','Net Profit'],
'restaurant.salariesPaid':['Ödənilmiş maaşlar','Выплаченные зарплаты','Salaries Paid'],
'restaurant.businessExpenses':['Biznes xərcləri','Бизнес расходы','Business Expenses'],
'restaurant.revenue':['Gəlir','Доход','Revenue'],
'restaurant.revenueByHour':['Saatlıq gəlir','Доход по часам','Revenue by Hour'],
'restaurant.revenueGenerated':['Yaradılmış gəlir','Полученный доход','Revenue Generated'],
'restaurant.dynamicHourlySalesPerformance':['Saatlıq satış dinamikası','Динамика продаж по часам','Hourly Sales Performance'],
'restaurant.peakHour':['Pik saat','Пиковый час','Peak Hour'],
'restaurant.fromYesterday':['dünənə nisbətən','по сравнению с вчера','from yesterday'],
'restaurant.rankedByRevenue':['Gəlirə görə sıralanıb','По доходу','Ranked by Revenue'],
'restaurant.waiterPerformance':['Ofisiant performansı','Производительность официантов','Waiter Performance'],
'restaurant.topZones':['Ən yaxşı zonalar','Лучшие зоны','Top Zones'],
'restaurant.top':['ən yaxşı','лучший','top'],
'restaurant.seatings':['Oturmalar','Посадки','Seatings'],
'restaurant.avgTime':['Ort. vaxt','Ср. время','Avg Time'],
'restaurant.guestsTotal':['qonaq','гостей','guests'],
'restaurant.zoneTable':['Zona / Masa','Зона / Стол','Zone / Table'],
'restaurant.downloadReport':['Hesabatı yüklə','Скачать отчёт','Download Report'],
'restaurant.mo':['Be','Пн','Mo'],
'restaurant.tu':['Ça','Вт','Tu'],
'restaurant.we':['Çə','Ср','We'],
'restaurant.th':['Cü','Чт','Th'],
'restaurant.fr':['Cü','Пт','Fr'],
'restaurant.sa':['Şə','Сб','Sa'],
'restaurant.su':['Ba','Вс','Su'],
};

const files = ['src/locales/az.json','src/locales/ru.json','src/locales/en.json'];
files.forEach((file, idx) => {
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  let updated = 0;
  for (const [key, vals] of Object.entries(tr)) {
    const parts = key.split('.');
    let cur = json;
    for (let i = 0; i < parts.length - 1; i++) {
      if (!cur[parts[i]]) cur[parts[i]] = {};
      cur = cur[parts[i]];
    }
    // Always overwrite with proper translation
    cur[parts[parts.length - 1]] = vals[idx];
    updated++;
  }
  fs.writeFileSync(file, JSON.stringify(json, null, 2) + '\n');
  console.log(`${file}: updated ${updated} keys`);
});
console.log('Done!');
