import { LayoutDashboard, Users, Package, DollarSign, Receipt, ChefHat, Activity, GraduationCap, Phone, MessageSquare, ShoppingCart, Car, Bed, Laptop } from 'lucide-react';

// Master registry of all available modules in the platform
// This is the single source of truth for module metadata
export const MODULE_REGISTRY = {
  dental: {
    id: 'dental',
    nameKey: 'sidebar.dental',
    descriptionKey: 'modules.dentalDesc',
    icon: Activity,
    path: '/dental',
    color: 'hover:text-cyan-600 hover:bg-cyan-50',
    accentColor: 'cyan',
    activeBg: 'bg-cyan-600',
    activeShadow: 'shadow-cyan-500/30',
    activeText: 'text-cyan-600',
    price: 49,
    isFree: false,
    isCore: false,
  },
  education: {
    id: 'education',
    nameKey: 'sidebar.education',
    descriptionKey: 'modules.educationDesc',
    icon: GraduationCap,
    path: '/education',
    color: 'hover:text-purple-600 hover:bg-purple-50',
    accentColor: 'purple',
    activeBg: 'bg-purple-600',
    activeShadow: 'shadow-purple-500/30',
    activeText: 'text-purple-600',
    price: 39,
    isFree: false,
    isCore: false,
  },
  crm: {
    id: 'crm',
    nameKey: 'sidebar.crm',
    descriptionKey: 'modules.crmDesc',
    icon: Users,
    path: '/crm',
    color: 'hover:text-rose-600 hover:bg-rose-50',
    accentColor: 'rose',
    activeBg: 'bg-rose-600',
    activeShadow: 'shadow-rose-500/30',
    activeText: 'text-rose-600',
    price: 29,
    isFree: false,
    isCore: false,
  },
  warehouse: {
    id: 'warehouse',
    nameKey: 'sidebar.warehouse',
    descriptionKey: 'modules.warehouseDesc',
    icon: Package,
    path: '/warehouse',
    color: 'hover:text-amber-600 hover:bg-amber-50',
    accentColor: 'amber',
    activeBg: 'bg-amber-500',
    activeShadow: 'shadow-amber-500/30',
    activeText: 'text-amber-600',
    price: 29,
    isFree: false,
    isCore: false,
  },
  restaurant: {
    id: 'restaurant',
    nameKey: 'sidebar.restaurant',
    descriptionKey: 'modules.restaurantDesc',
    icon: ChefHat,
    path: '/restaurant',
    color: 'hover:text-emerald-600 hover:bg-emerald-50',
    accentColor: 'emerald',
    activeBg: 'bg-emerald-600',
    activeShadow: 'shadow-emerald-500/30',
    activeText: 'text-emerald-600',
    price: 39,
    isFree: false,
    isCore: false,
  },
  finance: {
    id: 'finance',
    nameKey: 'sidebar.finance',
    descriptionKey: 'modules.financeDesc',
    icon: DollarSign,
    path: '/finance',
    color: 'hover:text-green-600 hover:bg-green-50',
    accentColor: 'green',
    activeBg: 'bg-green-600',
    activeShadow: 'shadow-green-500/30',
    activeText: 'text-green-600',
    price: 29,
    isFree: false,
    isCore: false,
  },
  callCenter: {
    id: 'callCenter',
    nameKey: 'sidebar.callCenter',
    descriptionKey: 'modules.callCenterDesc',
    icon: Phone,
    path: '/call-center',
    color: 'hover:text-indigo-600 hover:bg-indigo-50',
    accentColor: 'indigo',
    activeBg: 'bg-indigo-600',
    activeShadow: 'shadow-indigo-500/30',
    activeText: 'text-indigo-600',
    price: 19,
    isFree: false,
    isCore: false,
  },
  eTaxes: {
    id: 'eTaxes',
    nameKey: 'sidebar.etaxes',
    descriptionKey: 'modules.eTaxesDesc',
    icon: Receipt,
    path: '/dashboard/e-taxes',
    color: 'hover:text-sky-600 hover:bg-sky-50',
    accentColor: 'sky',
    activeBg: 'bg-sky-600',
    activeShadow: 'shadow-sky-500/30',
    activeText: 'text-sky-600',
    price: 19,
    isFree: false,
    isCore: false,
  },
  integrations: {
    id: 'integrations',
    nameKey: 'sidebar.integrations',
    descriptionKey: 'modules.integrationsDesc',
    icon: MessageSquare,
    path: '/integrations',
    color: 'hover:text-violet-600 hover:bg-violet-50',
    accentColor: 'violet',
    activeBg: 'bg-violet-600',
    activeShadow: 'shadow-violet-500/30',
    activeText: 'text-violet-600',
    price: 29,
    isFree: false,
    isCore: false,
  },
  retail: {
    id: 'retail',
    nameKey: 'sidebar.retail',
    descriptionKey: 'modules.retailDesc',
    icon: ShoppingCart,
    path: '/retail',
    color: 'hover:text-orange-600 hover:bg-orange-50',
    accentColor: 'orange',
    activeBg: 'bg-orange-500',
    activeShadow: 'shadow-orange-500/30',
    activeText: 'text-orange-600',
    price: 39,
    isFree: false,
    isCore: false,
  },
  fleet: {
    id: 'fleet',
    nameKey: 'sidebar.fleet',
    descriptionKey: 'modules.fleetDesc',
    icon: Car,
    path: '/fleet',
    color: 'hover:text-teal-600 hover:bg-teal-50',
    accentColor: 'teal',
    activeBg: 'bg-teal-600',
    activeShadow: 'shadow-teal-500/30',
    activeText: 'text-teal-600',
    price: 49,
    isFree: false,
    isCore: false,
  },
  hotels: {
    id: 'hotels',
    nameKey: 'sidebar.hotels',
    descriptionKey: 'modules.hotelsDesc',
    icon: Bed,
    path: '/hotels',
    color: 'hover:text-pink-600 hover:bg-pink-50',
    accentColor: 'pink',
    activeBg: 'bg-pink-600',
  },
  cyberCafe: {
    id: 'cyberCafe',
    nameKey: 'sidebar.cyberCafe',
    descriptionKey: 'modules.cyberCafeDesc',
    icon: Laptop,
    path: '/cyber-cafe',
    color: 'hover:text-purple-600 hover:bg-purple-50',
    accentColor: 'purple',
    activeBg: 'bg-purple-600',
    activeShadow: 'shadow-purple-500/30',
    activeText: 'text-purple-600',
    price: 39,
    isFree: false,
    isCore: false,
  },
};

// Get the navigation-ready array from active modules
export const getNavItemsFromModules = (t, activeModuleIds) => {
  return Object.values(MODULE_REGISTRY)
    .filter(mod => mod.isCore || activeModuleIds.includes(mod.id))
    .map(mod => ({
      id: mod.id,
      name: t(mod.nameKey) || mod.id,
      icon: mod.icon,
      path: mod.path,
      color: mod.color,
      activeBg: mod.activeBg,
      activeShadow: mod.activeShadow,
      activeText: mod.activeText,
    }));
};
